//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Circolare2018.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEACHING
    {
        public int ID { get; set; }
        public int ID_Resource { get; set; }
        public int ID_Course { get; set; }
        public string Notes { get; set; }
    
        public virtual COURSE COURSE { get; set; }
        public virtual RESOURCE RESOURCE { get; set; }
    }
}
