//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Circolare2018.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    using Circolare2018.Entities;
    
    public partial class DB_SiWeb3Entities : DbContext
    {
        public DB_SiWeb3Entities()
            : base("name=DB_SiWeb3Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<COURSE> COURSE { get; set; }
        public virtual DbSet<RESOURCE> RESOURCE { get; set; }
        public virtual DbSet<SUBSCRIPTION> SUBSCRIPTION { get; set; }
        public virtual DbSet<TEACHING> TEACHING { get; set; }
    
        public virtual ObjectResult<string> SetUserName(string name, string surname)
        {
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            var surnameParameter = surname != null ?
                new ObjectParameter("surname", surname) :
                new ObjectParameter("surname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("SetUserName", nameParameter, surnameParameter);
        }
    }
}
